/*
https://www.hackerearth.com/problem/algorithm/the-game-of-oxa-bb3d2676/
https://www.hackerearth.com/problem/algorithm/the-three-musketeers-6efd5f2d/
sieve questions :
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa2FVTDBCRHBWT09qejV4Z3BGSWt4Qk4tTUpUZ3xBQ3Jtc0ttaGhGRGJ1ZDhKWTJ4aE9DS29mRTZCbGlSVWV0Q2ZpRkp0MUFLalo4RzdVNm1uYjdOOXl5b3JVVk54SHZXZ3F1RXBXS0Nhb0M3dFJSckRaYnB1T3hiVExpZzlaTkkydmJWd3RheEZDb1ptUDJmcVAyWQ&q=https%3A%2F%2Fwww.hackerearth.com%2Fpractice%2Fmath%2Fnumber-theory%2Fbasic-number-theory-2%2Fpractice-problems%2F&v=acm6Nnpvgmg
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbU83SFNXcWhXN2VfaU5lbWNYd3l6T0hzM0FLZ3xBQ3Jtc0ttR0ZabjdKa0dNYTVUMkRLV1FwOVZSZ1FvdTZMQTdnelN0eWhscE4tVjhXc1NDZXV0eE5YSzVSTkc5c2dXcWNIWGgxNmlhUF9LcWdTUDdfYnJ0TnR3RmpkN2NjODNuQUpoNGJZUkxLRGFvNjlMSTBYcw&q=https%3A%2F%2Fcodeforces.com%2Fcontest%2F776%2Fproblem%2FB&v=acm6Nnpvgmg
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbmlWNUlYaUtQZGIydklkblF2TGxOUms4VjFhUXxBQ3Jtc0trQ1hZQmo1QW5haGlzR2pOVTZWZGpoOExfa2JCSVl5VmluLVFoQnFoXzh6WHVJSHM0dENvdWFQOTloeF9Dd3A2Y1pZME5EOE94dlFjVGdNREw2QS1Ma2NUd0tXUGlyQXpBbkh4enFjZTlmZHhRQzNzTQ&q=https%3A%2F%2Fcodeforces.com%2Fproblemset%2Fproblem%2F230%2FB&v=acm6Nnpvgmg
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbUZ3WkVlYU15SFdQeUU5dXY5V2dSTDczTW0tZ3xBQ3Jtc0tsdjFNV3pKNXdWa0xHSEJnU294OE1oaHc5WnZRajQ4aFgzRFd0d3BkRWxfTjNIbDBjaGNwSkE4azFGX0dteFpqZjhGWXhMSmdDSzNlUkRKenhsa01wWURSNUpVVVpablI3RVV4VWpzOWpoRTF2ZHlNMA&q=https%3A%2F%2Fleetcode.com%2Fproblems%2Fcount-primes%2F&v=acm6Nnpvgmg
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa3VkdWluYzcxWkt5enRUQVJtT29EZWROQmozZ3xBQ3Jtc0ttYUl3MF9LUW9pbmJlOWpsRDRKZzFJVUstV1lkVU1SbUZoNEFWdThXbDRmLVZDRTVBRXZuRkd2X1ZZSnFsZGgxTzA5SkRUaWV2OE9NUlZvV00tNEdmU0hnckFmelRjdW1VdXZRZjRNcHZXbDhWNTdVNA&q=https%3A%2F%2Fwww.hackerearth.com%2Fproblem%2Falgorithm%2Fmonk-and-divisor-conundrum-56e0eb99%2F&v=acm6Nnpvgmg
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbldUNFR0NVZIVnlXQTdsY3NNNTZDYkZCbVJFZ3xBQ3Jtc0trTTdYREI1c3ZZN3BnS0xTWWdXc2FvN3lsVk5xdG1zc0QxWkRvTHptRXdISTBqNlRHcTJnU3VxMl9jLW5Zem1CVDJiUzQ1QXNhM0dIM250VmNrcHBTLVZzcXNqa0Y1eEJ0Z3I1dk1jVU1LeW53aDFjdw&q=https%3A%2F%2Fwww.hackerearth.com%2Fpractice%2Fmath%2Fnumber-theory%2Fbasic-number-theory-2%2Fpractice-problems%2Falgorithm%2Fhacker-with-prime-bebe28ac%2F&v=acm6Nnpvgmg
modular questions :
https://codebuddy.co.in/problems/NTHTERM
http://www.spoj.com/problems/MAS/
http://www.spoj.com/problems/ZSUM/
https://www.codechef.com/problems/CHMOD
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbnlsRTlvdnhRbG5manVyNVh4QXpKbmNMckU0QXxBQ3Jtc0tuRVdDUmZDeGwzVXVtamlrWjRtTVJqTXVYaG1HLW5iTUhDUEc0MFNkXzBJVV9SYVY2N3Awa2JiZ2t4allmVTItQWgtRVpxc3lfOUp3X1BjbmFYc3E5UDVqWW9OR0FFSjRXWXlFWFN3SFJQODM1MkNzbw&q=https%3A%2F%2Fcodebuddy.co.in%2Fproblems%2FDQUERIES&v=Ljo4tWiuZL0
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa015SlZHZjg1UW5DLWFOWEFlVVNiTmVfbDg4UXxBQ3Jtc0treUh3SW1Xb3c5NGpYMHVXZElUTk5hNlJhWkJFeDNuU0ZGa0RVR1lZdi04RWZGdlktZ2xnY3dmcXV5WmhkNHQ3UVlMN3ZDRWFta1NIYnpCTzJfMl8tMDZQQnlZdU9HT0doZTFQcnFsd05GR3NUbkFRUQ&q=https%3A%2F%2Fcodebuddy.co.in%2Fproblems%2FBIGPOWERS&v=Ljo4tWiuZL0
*/